- name: Solana validator infra
  hosts: validators
  tasks:
    - name: Ping host
      ansible.builtin.ping:

    - name: Add the user 'sol' with a specific and a primary group of 'admin'
      ansible.builtin.user:
        name: sol
        group: admin



