- name: Solana validator infra
  hosts: validators
  tasks:
    - name: Ping validators hosts
      ansible.builtin.ping:

    - name: Upgrade all apt packages
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Add the user 'sol' with a specific and a primary group of 'admin'
      ansible.builtin.user:
        name: sol
        group: sol
        generate_ssh_key: yes

    - name: 'Create ramdisk and mount to fstab'
      mount:
        path: /mnt/ramdisk
        src: tmpfs
        fstype: tmpfs
        opts: rw,noexec,nodev,nosuid,noatime,size=16G,user=sol
        state: mounted

    # source: https://gist.github.com/devster31/74e48cc1c8e73c637bc7
    - name: Create swap spillover file
      sudo: yes
      command: dd if=/dev/zero of=/swapfile bs=1M count=16K

    - name: set permissions on swap file
      sudo: yes
      file:
        path: /swapfile
        mode: 0600

    - name: format swap file
      sudo: yes
      command: mkswap /swapfile

    - name: 'Create swap spillover file and mount to fstab'
      mount:
        path: none
        src: /swapfile
        fstype: swap
        opts: sw
        state: mounted
