- name: Solana validator infra
  hosts: validators
  remote_user: sol

  vars:
    swap_file_path: /swapfile
    swap_file_size_mb: '16384' # 16G, must be exact megabytes -> https://www.gbmb.org/gb-to-mb
    swap_swappiness: '1'

  roles:
    # role to handle swap files. source: https://galaxy.ansible.com/geerlingguy/swap
    - geerlingguy.swap

  tasks:
    - name: Ping validators hosts
      become: true
      ansible.builtin.ping:

    - name: Upgrade all apt packages
      become: true
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Add the user 'sol'
      become: true
      ansible.builtin.user:
        name: sol
        group: sol
        generate_ssh_key: yes

    - name: Create ramdisk and mount to fstab
      become: true
      ansible.posix.mount:
        path: /mnt/ramdisk
        src: tmpfs
        fstype: tmpfs
        opts: rw,noexec,nodev,nosuid,noatime,size=16G,user=sol
        state: mounted

    - name: Install solana
      become: true
      ansible.builtin.shell: sh -c "$(curl -sSfL https://release.solana.com/v1.14.10/install)"

    - name: Config solana to devnet
      ansible.builtin.shell: solana config set --url devnet

    - name: Create validator wallet owner account
      ansible.builtin.shell: solana-keygen new --outfile ~/wallet-keypair.json

    - name: Create validator identity account
      ansible.builtin.shell: solana-keygen new --outfile ~/validator-keypair.json

    - name: Set validator identity
      ansible.builtin.shell: solana config set --keypair ~/validator-keypair.json

    - name: Create validator vote account
      ansible.builtin.shell: solana-keygen new --outfile ~/vote-account-keypair.json

    - name: Config vote account
      ansible.builtin.shell: solana create-vote-account ~/vote-account-keypair.json ~/validator-keypair.json ~/wallet-keypair.json

    - name: Copy start-validator script
      ansible.builtin.copy:
        src: /scripts/start-validator.sh
        dest: ~/start-validator.sh
        owner: sol
        mode: '0755'

    - name: Create log folder
      ansible.builtin.shell: mkdir ~/log


