- name: Solana validator infra
  hosts: validators

  vars:
    swap_file_path: /swapfile
    swap_file_size_mb: '16384' # 16G, must be exact megabytes -> https://www.gbmb.org/gb-to-mb
    swap_swappiness: '1'

  roles:
    # role to handle swap files. source: https://galaxy.ansible.com/geerlingguy/swap
    - geerlingguy.swap

  tasks:
    - name: Ping validators hosts
      ansible.builtin.ping:

    - name: Upgrade all apt packages
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Add the user 'sol' with a specific and a primary group of 'admin'
      ansible.builtin.user:
        name: sol
        group: sol
        generate_ssh_key: yes

    - name: Create ramdisk and mount to fstab
      mount:
        path: /mnt/ramdisk
        src: tmpfs
        fstype: tmpfs
        opts: rw,noexec,nodev,nosuid,noatime,size=16G,user=sol
        state: mounted

    - name: Install solana
      command: sh -c "$(curl -sSfL https://release.solana.com/v1.14.10/install)"

    - name: Config solana to devnet
      command: solana config set --url devnet

    - name: Create validator identity account
      command: solana-keygen new --outfile ~/validator-keypair.json

    - name: Set validator identity account
      command: solana config set --keypair ~/validator-keypair.json

    - name: Create validator vote account
      command: solana-keygen new --outfile ~/vote-account-keypair.json

    - name: Config identity account
      command: solana create-vote-account ~/vote-account-keypair.json ~/validator-keypair.json ~/wallet-keypair.json

