# NOTE: Need to set authorized_key for .ssh sol user first

- name: Config sol user & validator identity
  hosts: validators
  become: true

  tasks:
    # Package needed for "ansible.builtin.expect" install python3-pip (python package manager)
    - name: Install python3-pip package
      ansible.builtin.apt:
        name: python3-pip
        state: present

    # Package needed for "ansible.builtin.expect" module, using pip installe (python)
    - name: Install pexpect package
      ansible.builtin.pip:
        name: pexpect

    - name: Set pubkey to authorized_keys for sol user
      become_user: sol
      authorized_key:
        user: sol
        state: present
        key: "{{ lookup('file', '~/.ssh/validator_rsa.pub') }}"

    - name: Install solana
      become_user: sol
      ansible.builtin.shell: sh -c "$(curl -sSfL https://release.solana.com/v1.14.12/install)"

    - name: Copy start-validator script
      become_user: sol
      ansible.builtin.copy:
        src: ../scripts/start-validator.sh
        dest: ~/start-validator.sh
        owner: sol
        group: sol
        mode: '0755'

    - name: Create log folder, if it does not exist
      become_user: sol
      ansible.builtin.file:
        path: ~/log
        state: directory
        mode: '0755'

    - name: Config solana to testnet
      become_user: sol
      ansible.builtin.shell: /home/sol/.local/share/solana/install/active_release/bin/solana config set --url https://api.testnet.solana.com
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Create validator wallet owner account
      become_user: sol
      ansible.builtin.shell:
        cmd: /home/sol/.local/share/solana/install/active_release/bin/solana-keygen new -o ~/wallet-keypair.json --no-bip39-passphrase
        creates: ~/wallet-keypair.json

    - name: Create validator identity account
      become_user: sol
      ansible.builtin.shell:
        cmd: /home/sol/.local/share/solana/install/active_release/bin/solana-keygen new -o ~/validator-keypair.json --no-bip39-passphrase
        creates: ~/validator-keypair.json

    - name: Set validator identity
      become_user: sol
      ansible.builtin.shell: /home/sol/.local/share/solana/install/active_release/bin/solana config set --keypair ~/validator-keypair.json
      args:
        executable: /bin/bash

    - name: Create validator vote account
      become_user: sol
      ansible.builtin.shell:
        cmd: /home/sol/.local/share/solana/install/active_release/bin/solana-keygen new -o ~/vote-account-keypair.json --no-bip39-passphrase
        creates: ~/vote-account-keypair.json

    - name: airdrop validator-keypair.json wallet
      become_user: sol
      ansible.builtin.shell: |
        VALIDATOR_ADDRESS=$(/home/sol/.local/share/solana/install/active_release/bin/solana ~/validator-keypair.json)

        /home/sol/.local/share/solana/install/active_release/bin/solana airdrop 1 $VALIDATOR_ADDRESS
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Config vote account
      become_user: sol
      ansible.builtin.shell: /home/sol/.local/share/solana/install/active_release/bin/solana create-vote-account ~/vote-account-keypair.json ~/validator-keypair.json ~/wallet-keypair.json
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Reboot the machine with all defaults
      ansible.builtin.reboot:
